services:
  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build: 
      context: ./backend
      dockerfile: go.dockerfile
    environment: 
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable"
    ports:
      - '8080:8080'
    depends_on: 
      - db

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

    

volumes:
  pgdata: {}
